### ISSUE TITLE
Not validating NS_AVAILABLE macro

### ISSUE THREAD

**Issue by bagage** [CyberAgent/iOS-NBUCore#6]
At least using SDK 9.2, another macro is used to limit API:

```
// in NSString.h
- (BOOL)containsString:(NSString *)str NS_AVAILABLE(10_10, 8_0);
```

This macro is not detected by NBUCore; I tried to hack a bit around that but even using the code below breaks compilation, probably caused by use of `__NBU_AVAILABILITY_STARTING`:
```
#undef  NS_AVAILABLE
#define NS_AVAILABLE(_mac, _ios) NS_AVAILABLE_IOS(_ios)
```

**Comment by bagage** [comment]
OK, got it! Will do a PR then.

**Comment by rivera-ernesto** [comment]
Nice!
